name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tracevt/leva:latest
      env:
        RAILS_ENV: test
        CI: true
        PG_PASSWORD: ${{ secrets.POSTGRES_TEST_PASSWORD }}
        PG_USER: ${{ secrets.POSTGRES_TEST_USER }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install required gems
      shell: bash
      run: bundle install

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.2.16

    - name: Precompile assets
      shell: bash
      run: |
        bun install --frozen-lockfile
        bundle exec rails assets:precompile

    - name: Start postgresql
      shell: bash
      run: |
        su postgres -c "/usr/bin/pg_ctlcluster 17 main start"
        su postgres -c "/usr/bin/pg_ctlcluster 17 main status"
        
        su - postgres -c "psql -c \"CREATE USER $PG_USER WITH CREATEDB PASSWORD '$PG_PASSWORD';\""

    - name: Update database.yml for CI
      run: |
        cp config/database.ci.yml config/database.yml

    - name: Database setup
      shell: bash
      run: |
        bin/rails db:drop
        bin/rails db:create
        bin/rails db:schema:load
        bin/rails db:migrate

    - name: Run RSpec tests
      shell: bash
      run: |
        bundle exec rspec