name: Rubocop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  rubocop_check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tracevt/leva:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install required gems
      run: bundle install --without development test

    - name: Run Rubocop
      run: |
        rubocop
